source-code/app/src/main/java/org/buildmlearn/toolkit/templates/FlashTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/InfoTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/LearnSpellingTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/QuizTemplate.java, source-code/app/src/main/res/values/strings.xml
1) I have changed the name of DELETE button to CANCEL in the Add new item dialog box.
2) When we press edit option, the dialog box was showing "Add new item". I changed its name to "Edit Item". I also changed the name of ADD, DELETE button to OK, CANCEL button respectively. 
I have made these changes for every templates.
=> Fixed Issue: #9, #20

source-code/app/src/main/AndroidManifest.xml
Fixed #39 : 
- Template Name is retained 
- Generation of APK successfully even on orientation change of App. 
- Content of Dialog retained
=> Retain of App State on Orientation Change

source-code/app/src/main/java/org/buildmlearn/toolkit/utilities/SignerThread.java
#50 , Added the feature to install(open) on clicking the notification.
=> Added: Feature to install the apk on clicking the notification

source-code/app/src/main/java/org/buildmlearn/toolkit/activity/TemplateEditor.java
Fixed Issue
#23 : Menu shows Save Template option two times
#24 : Simulate and Save Template options are added in menu list every time setting button is pressed
=> Fixed Issue : Problem with Menu in Edit Template

source-code/app/src/main/java/org/buildmlearn/toolkit/activity/TemplateActivity.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/LoadProjectFragment.java, source-code/app/src/main/res/menu/menu_project_selected.xml
#48 Deleting Feature added.
Here is a clip describing the feature introduced.
=> Added Project Deletion Feature

source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/SettingsFragment.java, source-code/app/src/main/res/xml/fragment_settings.xml
On Settings Page,
Summary for Your Name was Developer mode disables publishing of Apk to BuildmLearn Store
Now changed it to current username
=> Fixed, Wrong Summary Message under 'Your Name' in Settings

source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/NavigationDrawerFragment.java
=> Fixed Two Items Selected in Navigation Drawer

source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/NavigationDrawerFragment.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/SettingsFragment.java
=> Live Change of Username

source-code/app/src/main/AndroidManifest.xml, source-code/app/src/main/java/org/buildmlearn/toolkit/activity/TemplateEditor.java
- Fixed : #77 
- Added Toast after successfully saving of any Project
=> Fixed : Multiple instances of How to created

source-code/app/src/main/AndroidManifest.xml
=> Fixed : IntentFilter  Working for *.buildmlearn files

source-code/app/src/main/AndroidManifest.xml, source-code/app/src/main/java/org/buildmlearn/toolkit/activity/HomeActivity.java, source-code/app/src/main/java/org/buildmlearn/toolkit/activity/SettingsLinkerActivity.java, source-code/app/src/main/java/org/buildmlearn/toolkit/constant/Constants.java
Added #138 :  App's Settings link in Android Settings Menu.
=> Adding Intent Filter of App Settings

source-code/app/src/main/res/xml/fragment_settings.xml
As discussed in #122 , this PR will allow the users to have numeric and special characters in author name.
=> Allowing numeric or special characters in author name

source-code/app/src/main/java/org/buildmlearn/toolkit/ToolkitApplication.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/SettingsFragment.java
As mentioned in issue #22 there is no code for deleting temporary files!
=> Fixed Deleting Temporary Files!

source-code/app/src/main/java/org/buildmlearn/toolkit/learnspelling/SpellingActivity.java
=> Fixed Speech Speed Bug in SeekBar Simulator

source-code/app/src/main/java/org/buildmlearn/toolkit/learnspelling/DataManager.java, source-code/app/src/main/java/org/buildmlearn/toolkit/learnspelling/SpellingMainFragment.java
Fixed Issue #87 
Reset DataManager on Starting of Simulator rather than on Exit.
=> Wrong Result in Simulator Learn Spelling

source-code/app/src/main/java/org/buildmlearn/toolkit/utilities/SignerThread.java
=> Making apk with unexpected filename

source-code/app/src/main/java/org/buildmlearn/toolkit/templates/InfoAdapter.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/LearnSpellingAdapter.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/QuizAdapter.java
The negative button while editing any template should be 'cancel'  instead of delete
=> Cancel Button instead of delete button

source-code/app/src/main/java/org/buildmlearn/toolkit/ToolkitApplication.java, source-code/app/src/main/java/org/buildmlearn/toolkit/activity/TemplateEditor.java, source-code/app/src/main/java/org/buildmlearn/toolkit/adapter/DraftProjectAdapter.java, source-code/app/src/main/java/org/buildmlearn/toolkit/constant/Constants.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/DraftsFragment.java, source-code/app/src/main/java/org/buildmlearn/toolkit/model/SavedProject.java, source-code/app/src/main/java/org/buildmlearn/toolkit/model/Section.java, source-code/app/src/main/java/org/buildmlearn/toolkit/utilities/FileUtils.java, source-code/app/src/main/res/menu/menu_draft.xml, source-code/app/src/main/res/values/strings.xml
=> Implemented "My Drafts"

source-code/app/src/main/java/org/buildmlearn/toolkit/adapter/SavedProjectAdapter.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/LoadProjectFragment.java
=> Fixed Bug in Project Selection

source-code/app/src/main/java/org/buildmlearn/toolkit/adapter/SavedProjectAdapter.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/LoadProjectFragment.java, source-code/app/src/main/res/menu/menu_project.xml, source-code/app/src/main/res/values/array.xml, source-code/app/src/main/res/values/strings.xml
Sort by Project Name
Sort by Last Modified Time
Sort By Author Name
=> [Saved Projects] Implemented Sort

README.md
=> #159 Added a preview link of App

source-code/app/build.gradle, source-code/app/src/main/java/org/buildmlearn/toolkit/activity/FirstRunActivity.java, source-code/app/src/main/res/anim/bounceinup.xml
=> Reducing External dependencies

source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/SettingsFragment.java
=> Making the delete Temperory files AsyncTask

source-code/app/src/main/java/org/buildmlearn/toolkit/adapter/DraftProjectAdapter.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/DraftsFragment.java
Hey , I have a implemented the above enhancements. Please give a look. #196
=> Multi-deletion and Unselect-all implemented 

source-code/app/src/main/java/org/buildmlearn/toolkit/adapter/SavedApiAdapter.java, source-code/app/src/main/java/org/buildmlearn/toolkit/adapter/SavedProjectAdapter.java
Solving issue #209 
Author name gets displayed now.
@croozeus @opticod feedback ?
=> Adding Author name in project and apk fragment

source-code/app/src/main/java/org/buildmlearn/toolkit/activity/HomeActivity.java
=> Double back press to exit implemented.

source-code/app/src/main/java/org/buildmlearn/toolkit/activity/HomeActivity.java, source-code/app/src/main/java/org/buildmlearn/toolkit/adapter/TutorialAdapter.java, source-code/app/src/main/res/layout/tutorial_layout.xml, source-code/app/src/main/res/layout/tutorial_layout_finish.xml
=> Skip tutorial button added.

source-code/app/src/main/java/org/buildmlearn/toolkit/activity/TemplateEditor.java, source-code/app/src/main/java/org/buildmlearn/toolkit/model/TemplateInterface.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/ComprehensionAdapter.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/ComprehensionTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/DictationTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/FlashCardAdapter.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/FlashTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/InfoAdapter.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/InfoTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/LearnSpellingAdapter.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/LearnSpellingTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/MatchTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/QuizAdapter.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/QuizTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/VideoCollectionTemplate.java, source-code/app/src/main/res/layout/activity_template_editor.xml, source-code/app/src/main/res/values/strings.xml
@opticod  Now snackbar appears above navigation. issue #226
=> replaced confirm dialog with snackbar with UNDO button issue #226

source-code/app/src/main/java/org/buildmlearn/toolkit/activity/TemplateEditor.java, source-code/app/src/main/java/org/buildmlearn/toolkit/utilities/FileUtils.java
Hey ,I have fixed the issue by implementing a alert dialog which restricts user if user gives same name as already existing file.Please review it. #201
=> Fixed Issue #201

source-code/app/src/main/java/org/buildmlearn/toolkit/adapter/TutorialAdapter.java, source-code/app/src/main/res/layout/tutorial_layout.xml
@opticod 
Enhanced PR#238 as requested in issue #224 
Skip tutorial button is on all tutorials except the last one.
=> Skip tutorial button on every page.

source-code/app/src/main/java/org/buildmlearn/toolkit/templates/ComprehensionTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/DictationTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/FlashTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/InfoTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/LearnSpellingTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/MatchTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/QuizTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/VideoCollectionTemplate.java, source-code/app/src/main/res/values/strings.xml
=> Textfield validation added in templates.

source-code/app/src/main/java/org/buildmlearn/toolkit/activity/FirstRunActivity.java, source-code/app/src/main/java/org/buildmlearn/toolkit/activity/TemplateEditor.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/SettingsFragment.java, source-code/app/src/main/res/values/strings.xml
Hey , I have made validations for Template name, Author name and Username (in Settings and FirstRunActivity) to check for empty string or string with non alphanumeric starting character which looks like this now -
=> Validations added

source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/LoadApkFragment.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/LoadProjectFragment.java
@opticod 
I have improved the search functionality as reported in issue #257 
Please review the PR.
=> Search function improved.

source-code/app/src/main/java/org/buildmlearn/toolkit/flashcardtemplate/fragment/LastFragment.java, source-code/app/src/main/java/org/buildmlearn/toolkit/flashcardtemplate/fragment/MainFragment.java
=> Flash toolbar title corrected.

source-code/app/src/main/java/org/buildmlearn/toolkit/templates/ComprehensionTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/QuizTemplate.java, source-code/app/src/main/res/values/strings.xml
Fixes #198.
I have added the validations and implemented the suggestions from @opticod.
and Yes, Sorry for the delayed response. I was having some medical issues.
Thanks.
Here's a pic.
=> Validation for two or more options same in the Comprehension & Quiz Template.

source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/SettingsFragment.java
=> Fixed the Restore project Issue #175.

source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/LoadApkFragment.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/LoadProjectFragment.java
=> Fixed issue #273

source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/DraftsFragment.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/LoadApkFragment.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/LoadProjectFragment.java
Along with #276, also made the search case insensitive.
=> #276 FIXED: Issue with Search in SavedProjects and SavedAPKs + My Drafts

source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/DraftsFragment.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/LoadApkFragment.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/LoadProjectFragment.java
Fixes #268.
Now Toolkit informs the user about the number of items He/She has deleted.
=> Enhancing the delete feature.

source-code/app/src/main/java/org/buildmlearn/toolkit/templates/ComprehensionTemplate.java, source-code/app/src/main/res/values/strings.xml
#291
I have added a simple setError() message if time is zero because zero time should not be allowed anyway.
=> App crashes if time zero in Comprehension

source-code/app/src/main/java/org/buildmlearn/toolkit/adapter/DraftProjectAdapter.java, source-code/app/src/main/java/org/buildmlearn/toolkit/adapter/SavedApiAdapter.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/DraftsFragment.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/LoadApkFragment.java, source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/LoadProjectFragment.java, source-code/app/src/main/java/org/buildmlearn/toolkit/model/SavedApi.java, source-code/app/src/main/java/org/buildmlearn/toolkit/model/SavedProject.java
Fixed issue #271 
Same issue was present in Saved project and Saved APK fragments. In this PR they all are solved.
=> Fixed issue #271

source-code/app/src/main/java/org/buildmlearn/toolkit/fragment/SettingsFragment.java, source-code/app/src/main/res/values/strings.xml, source-code/app/src/main/res/xml/fragment_settings.xml
@opticod, Please have a look. ^^
=> Fixes #319. Added the rate_app in the settings fragment.

source-code/app/src/main/java/org/buildmlearn/toolkit/activity/HomeActivity.java
The number of exit toasts are set to one now.
=> Fixed exit toasts numbers

source-code/app/src/main/java/org/buildmlearn/toolkit/templates/MatchTemplate.java
@opticod 
Match template duplicacy fixed.
=> Match template input validation #303

source-code/app/src/main/java/org/buildmlearn/toolkit/activity/TemplateEditor.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/ComprehensionTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/DictationTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/FlashTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/InfoTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/LearnSpellingTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/MatchTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/QuizTemplate.java, source-code/app/src/main/java/org/buildmlearn/toolkit/templates/VideoCollectionTemplate.java
=> Fixed issue #226

source-code/app/src/main/java/org/buildmlearn/toolkit/activity/HomeActivity.java
=> Fixes: #331

source-code/app/src/main/java/org/buildmlearn/toolkit/templates/MatchTemplate.java
Fixed issue #326 
@opticod please review the PR.
=> Fixed option duplicacy in match template list and metadata delete issue in Comprehension and MatchTemplate issue

source-code/app/src/main/java/org/buildmlearn/toolkit/activity/TemplateEditor.java
#338   It is common problem for all the templates and now is fixed.
=> App Crash while creating APKs when template name already exits

source-code/app/src/main/java/org/buildmlearn/toolkit/activity/TemplateEditor.java
Now Single item is not allowed in Match template since it is illogical.
=> Single item not allowed in match

source-code/app/src/main/java/org/buildmlearn/toolkit/comprehensiontemplate/fragment/QuestionFragment.java, source-code/app/src/main/java/org/buildmlearn/toolkit/quiztemplate/fragment/QuestionFragment.java, source-code/app/src/main/res/layout/comprehension_content_question.xml, source-code/app/src/main/res/values/strings.xml
#346 
Added Clear Button in Comprehension and Quiz Template to allow user to unselect an option in question.
=> Added clear button in Comprehension and Quiz Template
